### ISSUE TITLE
How to use this with istio-system and prometheus (solution inside)

### ISSUE THREAD

**Issue by gabeleon** [qonto/prometheus-rds-exporter#235]
### Who it applies to

- If you use Istio
- If you have Prometheus within Istio-system

### What happens

- If you follow instructions to the letter, Prometheus will not scrape the metrics

### How to solve it

**After following the instructions to install it**, do the following:

1. Get your values.yaml for your currently deployed Prometheus system (usually something along these lines `helm get values RELEASE_NAME [flags]`)
2. Edit the values, under `additionalScrapeConfigs` insert an additional job_name:
```
    - job_name: prometheus-rds-exporter
      kubernetes_sd_configs:
      - namespaces:
          names:
          - monitoring 
        role: endpoints
```
3. Apply the edited values, in my case: `helm upgrade prometheus prometheus-community/kube-prometheus-stack -n istio-system -f values.yaml --version 62.2.1` (add the repo if you haven't on helm, and change the repo if you're using another version).
4. Edit the service monitor yaml `kubectl edit servicemonitor prometheus-rds-exporter-prometheus-rds-exporter-chart -n <NAMESPACE>`
5. Remove `spec.job_label`.
6. Done.

By adding the new job in step 2, it should now be visible in Prometheus' Service Discovery, and by removing the Job, it should now be in Prometheus' Target.
