### ISSUE TITLE
Allow restricting exporter scope to specific instances

### ISSUE THREAD

**Issue by mindw** [qonto/prometheus-rds-exporter#94]
**Is your feature request related to a problem? Please describe.**

I'm looking for exporting the output of `describe-db-instances` to prometheus. This promising project seems to fit the bill - except it returns metrics for _all_ RDS instances within  region. At least I could not an example on how to do it.

**Describe the solution you'd like**

Add an option to restrict exporter to an RDS instance(s) by - id, regex, tag (key/*, key/val,  key/regex)

**Describe alternatives you've considered**

Use the archived https://github.com/movio/aws-prometheus-exporter exporter to expose `describe-db-instances` output.

Thanks!

**Comment by vmercierfr** [comment]
Thanks for reporting this issue. In our initial use case, we needed to collect metrics from all RDS instances, but it makes sense to support instance filtering. We need to think about the way to implement it.

Can you provide more details on your ideal instance filters (e.g., on which RDS instance parameters you would like to filter)? If you can provide a concrete use case, it will help us a lot to design the feature.

---

Meanwhile, I see two possible workarounds:

- Use the `rds_instance_tags` metric (introduced in v0.5.0 for a similar issue https://github.com/qonto/prometheus-rds-exporter/issues/37) to filter Prometheus results, but metrics are still collected and stored in your Prometheus

- Use [metric_relabel_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) Prometheus parameter to drop useless metrics, but metrics are still fetched from AWS APIs

  ```yaml
  scrape_configs:
    - job_name: 'rds-exporter'
      static_configs:
        - targets: ['rds-exporter:9043']
      metric_relabel_configs:
        - source_labels: [job, dbidentifier]
          separator: "@"
          regex: "rds-exporter@db[0-9]+" # Exclude all metrics collected by "rds-exporter" job that match "db[0-9]+" regexp
          action: drop
  ```
